#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# profile
#zmodload zsh/zprof

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


# Add homebrew to the completion path
fpath=("/usr/local/bin/" $fpath)

# add zsh completions to path
fpath=(/usr/local/share/zsh-completions $fpath)

fpath=("$HOME/.local/bin" $fpath)

# why would you type 'cd dir' if you could just type 'dir'?
setopt AUTO_CD

# turn on fasd dir/file switcher
eval "$(fasd --init auto)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# Set Spaceship ZSH as a prompt
SPACESHIP_PROMPT_ORDER=(user host dir git node docker venv exec_time line_sep jobs exit_code char)
#SPACESHIP_RPROMPT_ORDER=(time)
#SPACESHIP_CHAR_SYMBOL=⮀
SPACESHIP_CHAR_SYMBOL=♥
SPACESHIP_CHAR_SUFFIX=\  
#SPACESHIP_TIME_SHOW=true
autoload -U promptinit; promptinit
prompt spaceship

#eval "$(starship init zsh)"

# Better node repl
# alias node="NODE_NO_READLINE=1 rlwrap -ppurple -S \"► \" node"

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
# [[ -f /Users/jg/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/jg/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
# [[ -f /Users/jg/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/jg/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh
# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
# [[ -f /Users/jg/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.zsh ]] && . /Users/jg/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.zsh


alias f="fuck"
eval $(thefuck --alias)


if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# Added by Amplify CLI binary installer
export PATH="$HOME/.amplify/bin:$PATH"


# iterm darkmode toggle
if [[ "$(uname -s)" == "Darwin" ]]; then
    sith() {
        val=$(defaults read -g AppleInterfaceStyle 2>/dev/null)
        if [[ $val == "Dark" ]]; then
            i
        fi
    }

    i() {
        if [[ $ITERM_PROFILE == "Default" ]]; then
            echo -ne "\033]50;SetProfile=Dark\a"
            export ITERM_PROFILE="Dark"
        else
            echo -ne "\033]50;SetProfile=Default\a"
            export ITERM_PROFILE="Default"
        fi
    }

    sith
fi

#zprof
