#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# profile
# zmodload zsh/zprof

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


# Add homebrew to the completion path
fpath=("/usr/local/bin/" $fpath)

# add zsh completions to path
fpath=(/usr/local/share/zsh-completions $fpath)

fpath=("$HOME/.local/bin" $fpath)

# why would you type 'cd dir' if you could just type 'dir'?
setopt AUTO_CD

# turn on fasd dir/file switcher
eval "$(fasd --init auto)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# When getting nvm errors on shell startup check:
# https://github.com/nvm-sh/nvm/issues/1245
# NVM config
#export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Set Spaceship ZSH as a prompt
#SPACESHIP_PROMPT_ORDER=(user host dir git node docker exec_time line_sep jobs exit_code char)
#SPACESHIP_CHAR_SYMBOL=⮀
#SPACESHIP_CHAR_SUFFIX=\ 
#autoload -U promptinit; promptinit
#prompt spaceship

# Better node repl
# alias node="NODE_NO_READLINE=1 rlwrap -ppurple -S \"► \" node"

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/jg/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/jg/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/jg/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/jg/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh
# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[[ -f /Users/jg/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.zsh ]] && . /Users/jg/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.zsh



# Digital ocean tool completion
# source <(doctl completion zsh)


alias f="fuck"
eval $(thefuck --alias)

  # Set Spaceship ZSH as a prompt
  #autoload -U promptinit; promptinit
  #prompt spaceship


# zprof